[tool.poetry]
name = "foobar"
version = "0.1.0"
description = ""
authors = ["Birger Schacht"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
Django = "^5.0.6"
django-simple-history = "^3.7.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
